#ifndef GANTTCHARDLL_GLOBAL_H
#define GANTTCHARDLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GANTTCHARDLL_LIBRARY)
#  define GANTTCHARDLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GANTTCHARDLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GANTTCHARDLL_GLOBAL_H
